[tool.poetry]
name = "Pokemon Team Builder"
version = "0.1.0"
description = "Portfolio project which allows users to select Pokemon for a Team and receive type coverage analysis"
authors = ["Caleb Boswell <caboswell@rocketmail.com>"]
readme = "README.md"

[tool.poetry]
python = "^3.10.6"
fastapi = {extras = ["all"], version = "^0.103.1"}
sqlalchemy = "^2.0.20"

[tool.poetry.group.dev.dependencies]
pytest = "7.4.1"
pre-commit = "^3.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"